version: '3'
services:
  frontend:
    image: node:22
    container_name: frontend
    working_dir: /app
    command: npm run dev
    ports: 
      -"5000:5000"
    volumes:
      "./frontend:/app"
      
    
